{{- if .Values.loadbalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: joget-dx8-tomcat9-pv
  annotations:
    load-balancer.hetzner.cloud/location: hel1
spec:
  selector:
    app: joget-dx8-tomcat9
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
  {{- end }}