{{ if .Values.global.application }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.deployment.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      run: {{ .Values.application.deployment.name }}
  replicas: 1
  template:
    metadata:
      labels:
        run: {{ .Values.application.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.application.deployment.containers.name }}
          image: {{ .Values.global.gdbImageRepo }}:{{ .Values.application.deployment.containers.imageName }}
          imagePullPolicy: {{ .Values.application.deployment.containers.imagePullPolicy }}
          env:
            - name: ENV
              value: {{ .Values.global.ENV | quote }}
            - name: DATABASE_HOST
              value: {{ .Values.global.DATABASE_HOST | quote }}
            - name: DATABASE_NAME
              value: {{ .Values.global.DATABASE_NAME | quote }}
            - name: DATABASE_USERNAME
              value: {{ .Values.global.DATABASE_USERNAME | quote }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.global.DATABASE_PASSWORD | quote }}
            - name: REDIS_HOST
              value: {{ .Values.global.REDIS_HOST | quote }}
            - name: ALLOWED_HOSTS
              value: {{ .Values.global.ALLOWED_HOSTS | quote }}
            - name: CORS_ORIGIN_WHITELIST
              value: {{ .Values.global.CORS_ORIGIN_WHITELIST | quote }}
            - name: AUTH_SERVICE_TYPE_1
              value: {{ .Values.global.AUTH_SERVICE_TYPE_1 | quote }}
            - name: AUTH_SERVICE_REALM_1
              value: {{ .Values.global.AUTH_SERVICE_REALM_1 | quote }}
            - name: AUTH_SERVICE_BACKEND_URL_1
              value: {{ .Values.global.AUTH_SERVICE_BACKEND_URL_1 | quote }}
            - name: AUTH_SERVICE_PUBLIC_URL_1
              value: {{ .Values.global.AUTH_SERVICE_PUBLIC_URL_1 | quote }}
            - name: AUTH_SERVICE_ID_1
              value: {{ .Values.global.AUTH_SERVICE_ID_1 | quote }}
            - name: AUTH_SERVICE_NAME_1
              value: {{ .Values.global.AUTH_SERVICE_NAME_1 | quote }}
            - name: AUTH_SERVICE_CLIENT_ID_1
              value: {{ .Values.global.AUTH_SERVICE_CLIENT_ID_1 | quote }}
            - name: AUTH_SERVICE_CLIENT_SECRET_1
              value: {{ .Values.global.AUTH_SERVICE_CLIENT_SECRET_1 | quote }}
            - name: AUTH_SERVICE_CLIENT_SCOPE_1
              value: {{ .Values.global.AUTH_SERVICE_CLIENT_SCOPE_1 | quote }}
            - name: TRANSLATION_SERVICE_URL
              value: {{ .Values.global.TRANSLATION_SERVICE_URL | quote }}
            - name: AUTH_SERVICE_CLIENT_CALLBACK
              value: {{ .Values.global.AUTH_SERVICE_CLIENT_CALLBACK | quote }}
            - name: LANGUAGES
              value: {{ .Values.global.LANGUAGES | quote }}
            - name: DEMAND_AUTHORIZATION_HEADER
              value: {{ .Values.global.DEMAND_AUTHORIZATION_HEADER | quote }}
            - name: UPLOAD_FILE_SIZE_LIMIT
              value: {{ .Values.global.UPLOAD_FILE_SIZE_LIMIT | quote }}
            - name: APP_TITLE
              value: {{ .Values.global.APP_TITLE | quote }}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.service.name }}
  labels:
    run: {{ .Values.application.service.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.application.service.type }}
  selector:
    run: {{ .Values.application.service.name }}
  ports:
    - port: 8080
      targetPort: 3003
      protocol: TCP
      name: http            
{{ end }}            
