### Global Values if any ###
global:
  name: rapidpro

### Sub Charts Specific Values ###
rapidpro:
  enabled: true
  name: "rapidpro"
  template:
    labels:
      app: "rapidpro"
  containers:
    name: "rapidpro"
    image: sdehaan/rapidpro:v4
    imagePullPolicy: "Always"
    databaseUrl: "postgresql://postgres:postgres@postgresql/rapidpro"
    redisUrl: "redis://redis:6379/0"
  profiles: "container"
  service:
    name: rapidpro
    type: ClusterIP
    port: 8000
    targetPort: 8000

celeryBase:
  name: "celery-base"
  replicaCount: 1
  template:
    labels:
      app: "celery-base"
  containers:
    name: "celery-base"
    image: sdehaan/rapidpro:v4
    imagePullPolicy: "Always"
  profiles: "container"
  service:
    name: "celery-base"
    type: ClusterIP
    port: 8000
    targetPort: 8000
postgresql:    
  name: "postgresql"
  replicaCount: 1
  template:
    labels:
      app: "postgresql"
  containers:
    name: "postgresql"
    image: mdillon/postgis:9.6
    imagePullPolicy: "Always"
  statefulset:
    name: postgresql
    username: "postgres"
    password: "postgres"
    databaseName: "rapidpro"
    spec:
      mountPath: /var/lib/pgsql/data
      storage: 1Gi
  service:
    name: postgresql
    type: ClusterIP
    port: 5432
    selector:
      app: postgresql
    
redis:
  name: "redis"
  replicaCount: 1
  template:
    labels:
      app: "redis"
  containers:
    name: "redis"
    image: redis:alpine
    imagePullPolicy: "Always"
  statefulset:
    name: redis
    spec:
      mountPath: /rapidpro/media/
      storage: 1Gi
  service:
    name: "redis"
    type: ClusterIP
    port: 6379