apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.backend.containers.port }}
      targetPort: {{ .Values.backend.containers.port }}
  selector:
    app: {{.Values.backend.name}}
  clusterIP: None