---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.deployment.name }}-secrets"
  namespace: "{{ $.Release.Namespace }}"
stringData:
  keystorePassword: "{{ .Values.oidcKeystorePassword }}"
  paymentHubPrivateKey: "{{.Values.paymenthub.bb.jws_tenant_private_key}}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.deployment.name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.deployment.name }}"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Values.deployment.name }}"
    spec:
      containers:
        - name: "{{ .Values.deployment.containers.name }}"
          image: "{{ .Values.deployment.containers.image }}:{{ .Values.deployment.containers.imageTag }}"
          imagePullPolicy: {{ .Values.deployment.containers.imagePullPolicy }}
          env:
            - name: OIDC_JWK_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.deployment.name }}-secrets"
                  key: keystorePassword
            - name: JWS_TENANT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.deployment.name }}-secrets"
                  key: paymentHubPrivateKey
            - name: PAYMENT_MODE
              value: "{{ .Values.payment.config.mode }}"
            - name: USCT-BB
              value: "{{ .Values.payment.variables.source_bb_id }}"
            - name: GOVERNMENT_IDENTIFIER
              value: "{{ .Values.payment.variables.government_identifier }}"
            - name: PAYMENT_IM_BASE_URL
              value: "{{ .Values.payment.bb.im.base_url }}"
            - name: PAYMENT_IM_HEADER
              value: "{{ .Values.payment.bb.im.header }}"
            - name: PAYMENTHUB_ACCOUNT_MAPPER_URL
              value: "{{ .Values.paymenthub.bb.account_mapper_url }}"
            - name: PAYMENTHUB_BULK_CONNECTOR_URL
              value: "{{ .Values.paymenthub.bb.bulk_connector_url }}"
            - name: PAYMENT_CALLBACK_BASE_URL
              value: "{{ .Values.paymenthub.bb.callback_base_url }}"
            - name: PAYMENT_REGISTERING_INSTITUTION_ID
              value: "{{ .Values.paymenthub.bb.registering_institution_id }}"
            - name: PAYMENTHUB_TENANT
              value: "{{ .Values.paymenthub.bb.tenant }}"
            - name: PAYMENTHUB_PROGRAM_ID
              value: "{{ .Values.paymenthub.bb.program_id }}"
            - name: PAYMENTHUB_PAYMENT_MODE
              value: "{{ .Values.paymenthub.bb.payment_mode }}"
            - name: PAYMENTHUB_IM_HEADER
              value: "{{ .Values.paymenthub.bb.im.header }}"
            - name: CALLBACK_CIDR
              value: "{{ .Values.callback.cidr }}"
            - name: LOGGING_LEVEL_ROOT
              value: "{{ .Values.service.logLevel }}"
            - name: USCT_AUTHENTICATION
              value: "{{ .Values.service.authmode }}"
            - name: OPEN-IMIS_MODE
              value: "{{.Values.openImis.mode}}"
            - name: OPEN-IMIS_URL
              value: "{{ .Values.openImis.url}}"
            - name: OPEN-IMIS_EMULATOR-URL
              value: "{{ .Values.openImis.emulator_url}}"
            - name: OPEN-IMIS_USER
              value: "{{ .Values.openImis.user}}"
            - name: OPEN-IMIS_PASSWORD
              value: "{{ .Values.openImis.password}}"
            - name: OPEN-IMIS_HEADER
              value: "{{ .Values.openImis.header}}"
            - name: IGRANT_URL
              value: "{{.Values.igrant.url}}"
            - name: IGRANT_TOKEN
              value: "{{.Values.igrant.token}}"
            - name: IGRANT_DATA_AGREEMENT_ID
              value: "{{.Values.igrant.dataAgreementId}}"
            - name: IGRANT_HEADER
              value: "{{.Values.igrant.header}}"
            - name: IGRANT_MODE
              value: "{{.Values.igrant.mode}}"
