apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.payment_bb_emulator.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.payment_bb_emulator.labels.app }}
spec:
  selector:
    app: {{ .Values.payment_bb_emulator.labels.app  }}
  ports:
    - port: {{ .Values.payment_bb_emulator.service.port }}
      protocol: TCP

