{{- if .Values.restartSchedule.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kill-pod-cronjob
spec:
  schedule: "1 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kill-pods
              image: bitnami/kubectl:latest
              command: ["kubectl"]
              args: ["delete", "pod", "-l", "app={{ .Values.deployment.name }}", "-n", "{{ $.Release.Namespace }}"]
          restartPolicy: Never
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "{{ $.Release.Namespace }}"
  name: pod-deleter
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-deleter-binding
  namespace: "{{ $.Release.Namespace }}"
subjects:
  - kind: ServiceAccount
    name: default
    namespace: "{{ $.Release.Namespace }}"
roleRef:
  kind: Role
  name: pod-deleter
  apiGroup: rbac.authorization.k8s.io
  {{end}}