global:
  namespace: "${NAMESPACE}"
  gdbImageRepo: "${ECR_GDB_REPO}"
  db: ${DATABASE_ENABLED}
  secret: ${SECRETS_ENABLED}
  application: ${APPLICATION_ENABLED}
  PGDATA: "${PGDATA}"
  ENV: "${ENV}"
  DATABASE_HOST: "${DATABASE_HOST}"
  DATABASE_NAME: "${DATABASE_NAME}"
  DATABASE_USERNAME: "${DATABASE_USERNAME}"
  DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
  REDIS_HOST: "${REDIS_HOST}"
  ALLOWED_HOSTS: "${ALLOWED_HOSTS}"
  CORS_ORIGIN_WHITELIST: "${CORS_ORIGIN_WHITELIST}"
  AUTH_SERVICE_TYPE_1: "${AUTH_SERVICE_TYPE_1}"
  AUTH_SERVICE_REALM_1: "${AUTH_SERVICE_REALM_1}"
  AUTH_SERVICE_BACKEND_URL_1: "${AUTH_SERVICE_BACKEND_URL_1}"
  AUTH_SERVICE_PUBLIC_URL_1: "${AUTH_SERVICE_PUBLIC_URL_1}"
  AUTH_SERVICE_ID_1: "${AUTH_SERVICE_ID_1}"
  AUTH_SERVICE_NAME_1: "${AUTH_SERVICE_NAME_1}"
  AUTH_SERVICE_CLIENT_ID_1: "${AUTH_SERVICE_CLIENT_ID_1}"
  AUTH_SERVICE_CLIENT_SECRET_1: "${AUTH_SERVICE_CLIENT_SECRET_1}"
  AUTH_SERVICE_CLIENT_SCOPE_1: "${AUTH_SERVICE_CLIENT_SCOPE_1}"
  TRANSLATION_SERVICE_URL: "${TRANSLATION_SERVICE_URL}"
  AUTH_SERVICE_CLIENT_CALLBACK: "${AUTH_SERVICE_CLIENT_CALLBACK}"
  LANGUAGES: "${LANGUAGES}"
  DEMAND_AUTHORIZATION_HEADER: "${DEMAND_AUTHORIZATION_HEADER}"
  UPLOAD_FILE_SIZE_LIMIT: "${UPLOAD_FILE_SIZE_LIMIT}"
  APP_TITLE: "${APP_TITLE}"


gdb:
  enabled: ${GDB_ENABLED}
