apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
  labels:
    app: {{ .Values.db.name }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.db.containers.port }}
      targetPort: {{ .Values.db.containers.port }}

  selector:
    app: {{.Values.db.name}}
  clusterIP: None