name: "sandbox"
replicaCount: 1
labels: 
  app: "sandbox"
template:
  labels: 
    app: "sandbox"
containers:
  name: sandbox
  image: ghcr.io/govstackworkinggroup/sandbox-usecase-usct-frontend:roles-fix-3
  imagePullPolicy: "Always"
profiles: "container"
service:
  name: "sandbox"
  type: ClusterIP
  port: 80
  targetPort: 80
tls:
  dnsNames: "usct.playground.sandbox-playground.com"
  certificateName: "sandbox-tls"