apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-nginx
    spec:
      serviceAccountName: ingress-nginx
      containers:
        - name: controller
          image: registry.k8s.io/ingress-nginx/controller:v1.14.1
          args:
            - /nginx-ingress-controller
            - --publish-service=$(POD_NAMESPACE)/ingress-nginx-controller
            - --election-id=ingress-controller-leader
            - --ingress-class=nginx
            - --watch-ingress-without-class=false
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    service.beta.kubernetes.io/upcloud-load-balancer-config: |
      {
        "name": "black-white-lb",
        "frontends": [
          {
            "name": "https",
            "mode": "http",
            "port": 443,
            "tls_configs": [
              {
                "name": "0dfc806e-1137-43a5-b5b5-ed24c7ea5f8d-ingress-nginx-ingress-n-tls",
                "certificate_bundle_uuid": "0a598faf-b6f2-48c0-bee4-4cd7760e386d"
              }
            ]
          },
          {
            "name": "http",
            "mode": "http",
            "port": 80,
            "rules": [
              {
                "name": "redirect-to-https",
                "priority": 100,
                "matchers": [],
                "actions": [
                  {
                    "type": "http_redirect",
                    "action_http_redirect": {
                      "scheme": "https"
                    }
                  }
                ]
              }
            ]
          }
        ],
        "backends": [
          { "name": "https" },
          { "name": "http" }
        ]
      }
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 80