apiVersion: batch/v1
kind: CronJob
metadata:
  name: mock-sris
  labels:
    app: {{ .Values.deployment.name }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 61
      template:
        metadata:
          labels:
            app: {{ .Values.deployment.name }}
        spec:
          containers:
            - name: {{ .Values.deployment.containers.name }}
              image: {{ .Values.deployment.containers.image }}
          restartPolicy: OnFailure