{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: {{ .Values.frontend.labels.app }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.labels.app }}
  template:
    metadata:
      labels:
        app:  {{ .Values.frontend.labels.app }}
    spec:
      containers:
        - name: {{ .Values.frontend.spec.container.name }}
          image: "{{ .Values.frontend.spec.container.image }}:{{ .Values.frontend.spec.container.imageTag }}"
          imagePullPolicy: {{ .Values.frontend.spec.container.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
              name: server
          resources:
            limits:
              cpu: "500m"
              memory: 1Gi
            requests:
              cpu: "200m"
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}-service
  labels:
    app: {{ .Values.frontend.labels.app }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.frontend.labels.app }}
{{- end }}