apiVersion: batch/v1
kind: Job
metadata:
  name: openimis-migrate
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: openimis:govstack-seeds-1
          command: ["/bin/bash", "/scripts/entrypoint.sh", "manage", "migrate"]
          volumeMounts:
            - name: script-volume
              mountPath: /scripts/entrypoint.sh
              subPath: entrypoint.sh
              readOnly: true
      restartPolicy: OnFailure
      volumes:
        - name: script-volume
          configMap:
            name: openimis-script
