apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "2"
  name: {{ .Values.global.baserow.backendSecret }}
data:
{{- if .Values.minio.enabled }}
  AWS_ACCESS_KEY_ID: {{ include "minio.secret.userValue" .Subcharts.minio | b64enc }}
  AWS_SECRET_ACCESS_KEY:  {{ include "minio.secret.passwordValue" .Subcharts.minio | b64enc }}
{{- end }}
{{- if .Values.postgresql.enabled }}
  DATABASE_HOST: {{ include "postgresql.v1.primary.fullname" .Subcharts.postgresql | b64enc }}
  DATABASE_PORT: {{ include "postgresql.v1.service.port" .Subcharts.postgresql | b64enc }}
  DATABASE_NAME: {{ include "postgresql.v1.database" .Subcharts.postgresql | b64enc }}
  DATABASE_PASSWORD: {{ include "baserow.global.postgresql.password" . | b64enc }}
{{- end }}
{{- if .Values.redis.enabled }}
  REDIS_HOST: {{ printf "%s-master" (include "common.names.fullname" .Subcharts.redis) | b64enc }}
  REDIS_PORT:  {{ printf "%s" (tpl (toString .Values.redis.master.service.ports.redis) $) | b64enc }}
  REDIS_PASSWORD: {{ include "redis.password" .Subcharts.redis | b64enc  }}
{{- end }}
{{- if .Values.generateJwtSecret }}
  BASEROW_JWT_SIGNING_KEY: {{ include "baserow.global.jwt.signing_key" . | b64enc | quote }}
  SECRET_KEY: {{ include "baserow.global.jwt.secret_key" . | b64enc | quote }}
{{- end }}
{{- range $key, $val := .Values.backendSecrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
