{{- if .Values.global.baserow.serviceAccount.shared -}}
{{- if .Values.global.baserow.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "baserow.global.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "baserow.global.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "2"
  {{- with .Values.global.baserow.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.global.baserow.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}
