### Global Values if any ###
global:
  name: rapidpro

### Sub Charts Specific Values ###
rapidpro:
  enabled: true
  name: "rapidpro"
  template:
    labels: 
      app: "rapidpro"
  containers:
    name: "rapidpro"
    image: ghcr.io/govstackworkinggroup/sandbox-bb-messaging:stable
    imagePullPolicy: "IfNotPresent"
    databaseUrl: "postgresql://postgres:postgres@postgresql/rapidpro"
    redisUrl: "redis://redis:6379/0"
  profiles: "container"
  service:
    name: rapidpro
    type: ClusterIP
    port: 8000
    targetPort: 8000

postgresql:    
  name: "postgres"
  replicaCount: 1
  template:
    labels:
      app: "postgres"
  containers:
    name: "postgres"
    image: ghcr.io/baosystems/postgis:15-3.3
    imagePullPolicy: "IfNotPresent"
  statefulset:
    name: postgres
    username: "temba"
    password: "temba"
    databaseName: "temba"
    postgresPassword: "tembatemba"
    spec:
      mountPath: /var/lib/pgsql/data
      storage: 1Gi
  service:
    name: postgres
    type: ClusterIP
    port: 5432
    selector:
      app: postgres
    
redis:
  name: "redis"
  replicaCount: 1
  template:
    labels:
      app: "redis"
  containers:
    name: "redis"
    image: redis:6.2-alpine
    imagePullPolicy: "IfNotPresent"
  statefulset:
    name: redis
    spec:
      mountPath: /rapidpro/media/
      storage: 1Gi
  service:
    name: "redis"
    type: ClusterIP
    port: 6379