enabled: true
backend:
  name: threat-service
  containers:
    name: threat-service
    image: ghcr.io/govstackworkinggroup/sandbox-usecase-earlywarning-threatservice
    imageTag: be206511
    imagePullPolicy: IfNotPresent
    port: 8080

db:
  name: threat-db-service
  containers:
    name: threat-db-service
    imagePullPolicy: IfNotPresent
    username: sa
    password:
    driverClassName: org.h2.Driver
    databasePlatform: org.hibernate.dialect.H2Dialect
    database:
      url: jdbc:h2:file:./src/main/resources/db/data/threat;AUTO_SERVER=true

kafka:
  bootstrapServers: early-warnings-kafka:9092
  topic:
    name: threats-topic

userService:
  url: http://user-service:8080/api/v1/

restartSchedule:
  enabled: true