apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
type: Opaque
data:
  username: {{ randAlphaNum 32 | b64enc | quote }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kibana
type: Opaque
data:
  encryptionkey: {{ randAlphaNum 32 | b64enc | quote }}