apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.digital_registries_bb_emulator.name }}
  labels:
    {{- toYaml .Values.digital_registries_bb_emulator.labels | nindent 4 }}
spec:
  replicas: {{ .Values.digital_registries_bb_emulator.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.digital_registries_bb_emulator.template.labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.digital_registries_bb_emulator.template.labels | nindent 8 }}
    spec:
        containers:
        - name: {{ .Values.digital_registries_bb_emulator.container.name }}
          image: "{{ .Values.digital_registries_bb_emulator.container.image }}"
          imagePullPolicy: {{ .Values.digital_registries_bb_emulator.container.imagePullPolicy }}
          ports:
          - containerPort: 8080
            name: server
          env:
            - name: ACTIVE_PROFILES
              value: {{ .Values.digital_registries_bb_emulator.profiles }}
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: "200m"
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.digital_registries_bb_emulator.service.name }}-service
  labels:
    {{- toYaml .Values.digital_registries_bb_emulator.labels | nindent 4 }}
spec:
  type: {{ .Values.digital_registries_bb_emulator.service.type }}
  ports:
    - port: {{ .Values.digital_registries_bb_emulator.service.port }}
      targetPort: {{ .Values.digital_registries_bb_emulator.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.digital_registries_bb_emulator.labels | nindent 4 }}