{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.backend.name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.backend.name }}"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Values.backend.name }}"
    spec:
      containers:
        - name: "{{ .Values.backend.containers.name }}"
          image: "{{ .Values.backend.containers.image }}:{{ .Values.backend.containers.imageTag }}"
          imagePullPolicy: {{ .Values.backend.containers.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.containers.port }}
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.kafka.bootstrapServers }}
            - name: SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET
              value: earliest
            - name: SPRING_KAFKA_CONSUMER_ENABLE_AUTO_COMMIT
              value: "true"
            - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
              value: org.apache.kafka.common.serialization.StringDeserializer
            - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
              value: org.apache.kafka.common.serialization.StringDeserializer
            - name: SPRING_KAFKA_CONSUMER_PROPERTIES_REQUEST_TIMEOUT_MS
              value: "60000"
            - name: SPRING_KAFKA_CONSUMER_PROPERTIES_SESSION_TIMEOUT_MS
              value: "60000"
            - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
              value: org.apache.kafka.common.serialization.StringSerializer
            - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
              value: org.apache.kafka.common.serialization.StringSerializer
{{- end }}