= temp
== docs

By default, PostgreSQL listens on a Unix domain socket located at `/var/run/postgresql/.s.PGSQL.5432`. If the server is configured to use a different socket path or port, you’ll need to connect to that specific socket. Check the PostgreSQL configuration file (`postgresql.conf`) to  issues on your system. Let me know if you need further assistance!^[q^Cguration or permission


== Connect command

psql -U temba2 -d temba2 -h localhost -p 5432

temba:temba@postgres-service:5432/temba


- DATABASE_URL=localhost://temba:temba@postgresql:5432/temba


docker run -p 5432:5432 -e POSTGRES_HOST_AUTH_METHOD=trust postgis/postgis

docker run  -p 5432:5432 postgis/postgis -e POSTGRES_PASSWORD=temba POSTGRES_HOST_AUTH_METHOD=trust

docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=temba -e POSTGRES_HOST_AUTH_METHOD=trust postgis/postgis -v /var/lib/postgresql/data/pg_hba.conf

docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=temba -e POSTGRES_HOST_AUTH_METHOD=trust postgis/postgis

docker run -p 5432:5432  -e POSTGRES_HOST_AUTH_METHOD=trust -v /var/lib/postgresql/data:/var/lib/postgresql/data postgis/postgis

docker run test --network="host"

\dt

== Docs

Database is uninitialized and superuser password is not specified.
You must specify POSTGRES_PASSWORD to a non-empty value for the
superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".

You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
connections without a password. This is *not* recommended.



== Commands

kubectl exec rapidpro-57776cdc76-9pwnn -- nslookup postgresql.temprapid.svc.cluster.local

== sign up

login

http://localhost:8000/org/signup