apiVersion: v2
name: usct-umbrella
description: usct helm package
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: backend
    version: 0.1.0
    repository: file://charts/backend
    condition: backend.enabled
  - name: payment
    version: 0.1.0
    repository: file://charts/payment
    condition: payment.enabled
  - name: im-central-server
    version: 0.1.0
    repository: file://charts/im-central-server
    condition: im-central-server.enabled
  - name: im-security-server
    version: 0.1.0
    repository: file://charts/im-security-server
    condition: im-central-server.enabled
  - name: ui
    version: 0.1.0
    repository: file://charts/ui
    condition: ui.enabled
