apiVersion: v2
name: mock-sris
description: Backend driver of USCT MVP
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: backend
    version: 0.1.0
    repository: file://charts/backend
    condition: backend.enabled
