usct-backend:
  enabled: true
  deployment:
    containers:
      image: ghcr.io/govstackworkinggroup/sandbox-usecase-usct-backend:paymenthub-1

open-imis:
  enabled: true
  backend:
    service:
      name: open-imis-backend

information-mediator:
  enabled: true

usct-frontend:
  enabled: true
  containers:
    image: ghcr.io/govstackworkinggroup/sandbox-usecase-usct-frontend:latest

consentbb:
  enabled: true
  namespace: usct

ph-ee-g2psandbox:
  enabled: true
  ph-ee-engine:
    elasticsearch:
      imagePullPolicy: "IfNotPresent"
      volumeClaimTemplate:
        storageClassName: "hcloud-volumes"