apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.playground_frontend.name }}
  labels:
    {{- toYaml .Values.playground_frontend.labels | nindent 4 }}
spec:
  replicas: {{ .Values.playground_frontend.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.playground_frontend.template.labels | nindent 6 }}
  template:
    metadata:
      labels: 
        {{- toYaml .Values.playground_frontend.template.labels | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.playground_frontend.container.name }}
          image: "{{ .Values.playground_frontend.container.image }}:{{ .Values.playground_frontend.container.imageTag }}"
          imagePullPolicy: {{ .Values.playground_frontend.container.imagePullPolicy }}
          ports:
          - containerPort: 80
            name: server
          resources:
            limits:
              cpu: "500m"
              memory: 1Gi
            requests:
              cpu: "200m"
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.playground_frontend.service.name }}-service
  labels:
    {{- toYaml .Values.playground_frontend.labels | nindent 4 }}
spec:
  type: {{ .Values.playground_frontend.service.type }}
  ports:
    - port: {{ .Values.playground_frontend.service.port }}
      targetPort: {{ .Values.playground_frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.playground_frontend.labels | nindent 4 }}