apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.deployment.name }}-secrets"
  namespace: "{{ $.Release.Namespace }}"
stringData:
  keystorePassword: "{{ .Values.oidcKeystorePassword }}"
  paymentHubPrivateKey: "{{.Values.paymenthub.bb.jws_tenant_private_key}}"