apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.dbService.name }}
spec:
  type: ClusterIP
  ## Kubernetes assign a virtual IP dynamically
  ports:
    - port: {{ .Values.dbService.port }}
  selector:
    app: {{ .Values.dbStatefulset.name }}
  clusterIP: None
  ## headless service